<a href="https://colab.research.google.com/github/rohindth-08/Matrix-Calculator-/blob/main/Copy_of_Project_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Intermediate: Matrix Calculator – Develop a program that
performs addition, multiplication, determinant,
transpose and inverse operations on matrices. (Project-2)

In [ ]:
import numpy as np

In [ ]:
def add_mtrx(matA , matB):
  return np.add(matA , matB)

In [ ]:
def mul_mtrx(matA , matB):
  return np.dot(matA , matB)

In [ ]:
def det_mtrx(matA):
  return np.linalg.det(matA)

In [ ]:
def trans_mtrx(matA):
  return np.transpose(matA)

In [ ]:
def inverse_mtrx(matA):
  if det_mtrx(matA) == 0 :
    return "Inverse is not possible"
  return np.linalg.inv(matA)

In [ ]:

matA = np.array([[1,2],[3,4]])
matB = np.array([[5,6],[7,8]])

print(matA)
print("----------")
print(matB)


print("Addition of two matrices: ")
print(add_mtrx(matA , matB))
print("----------")
print("Multipication of the two matrices: ")
print(mul_mtrx(matA , matB))
print("----------")


print("Determinant of matrix A :")
print(det_mtrx(matA))
print("----------")
print("Determinant of matrix B :")
print(det_mtrx(matB))
print("----------")

print("Transpose of matrix A : ")
print(trans_mtrx(matA))
print("----------")
print("Transpose of matrix B")
print(trans_mtrx(matB))
print("----------")


print("Inverse of the Matrix A :")
print(inverse_mtrx(matA))
print("----------")
print("Inverse of the Matrix B :")
print(inverse_mtrx(matB))

[[1 2]
 [3 4]]
----------
[[5 6]
 [7 8]]
Addition of two matrices: 
[[ 6  8]
 [10 12]]
----------
Multipication of the two matrices: 
[[19 22]
 [43 50]]
----------
Determinant of matrix A :
-2.0000000000000004
----------
Determinant of matrix B :
-2.000000000000005
----------
Transpose of matrix A : 
[[1 3]
 [2 4]]
----------
Transpose of matrix B
[[5 7]
 [6 8]]
----------
Inverse of the Matrix A :
[[-2.   1. ]
 [ 1.5 -0.5]]
----------
Inverse of the Matrix B :
[[-4.   3. ]
 [ 3.5 -2.5]]
